quarkus:
  profile:
    parent: env
  jackson:
    fail-on-unknown-properties: true
  log:
    level: INFO
    category:
      "task.service":
        level: DEBUG

#Service port
  http:
    port: ${PORT}

#MongoDB config
  mongodb:
    connection-string: ${LOCAL_MONGO_URL}
    database: ${LOCAL_MONGO_DB}
