quarkus:
  profile:
    parent: env
  jackson:
    fail-on-unknown-properties: true
  log:
    level: INFO
    category:
      "task.service":
        level: DEBUG

  http:
    port: ${PORT}

  mongodb:
    connection-string: ${LOCAL_MONGO_URL}
    database: ${LOCAL_MONGO_DB}
    #username: myusername
    #password: mypassword
    authentication-database: ${LOCAL_MONGO_USER}

logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: INFO
