name: Format Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [main]

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run spotless check
        run: ./gradlew spotlessCheck
